# Generated by Django 3.0.8 on 2020-08-07 16:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_bids',
            name='bid_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Bid date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auction_comments',
            name='comment_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Comment date'),
            preserve_default=False,
        ),
    ]
