# Generated by Django 3.0.8 on 2020-08-07 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20200807_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listing',
            name='listing_date',
            field=models.DateTimeField(),
        ),
    ]
