# Generated by Django 3.0.8 on 2020-08-10 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_user_watchlist_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_listing',
            name='listing_image',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
    ]
