# Generated by Django 3.0.8 on 2020-08-11 20:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auction_listing_listing_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='watchlist_listing',
        ),
        migrations.AddField(
            model_name='auction_listing',
            name='watchlist_listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
