# Generated by Django 3.0.8 on 2020-08-12 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20200811_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction_listing',
            name='watchlist_listing',
        ),
        migrations.AddField(
            model_name='auction_listing',
            name='listed_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='watchlist',
            field=models.ManyToManyField(blank=True, related_name='watchlist', to='auctions.Auction_Listing'),
        ),
    ]
