# Generated by Django 3.0.8 on 2020-08-12 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20200812_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listing',
            name='listed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
